spring:
  application:
    name: prod


server:
  port: 25590
  servlet:
    context-path: /ai

### mysql
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bomc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver


### oracle
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@bomc-db:1521:root
#    username: root
#    password: root
#    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml





